### ISSUE TITLE
Broken OSV Integration 

### ISSUE THREAD

**Issue by VinodAnandan** [DependencyTrack/hyades#1023]
The integration with OSV in the Hyades project is currently broken,

**Steps to Reproduce**

- Configure OSV values in yaml 
	`VULNERABILITY_SOURCE_GOOGLE_OSV_ENABLED: "true" `
- Configure OSV Settings in UI, Select Ecosystem values.
- Configure OSV related task settings in UI.

**Expected Behavior**
The integration with OSV should work smoothly, allowing Hyades to mirror OSV vulnerabilities.

**Additional Information**
Version : master (18/01/2024)

**Comment by sahibamittal** [comment]
OSV integration works as expected when message to Kafka topic is sent manually (like using redpanda). But, it seems it is not triggering the event on scheduled basis on its own. Looking into it.

**Comment by sahibamittal** [comment]
When cron job scheduled via application.properties in apiserver, it is not triggering the mirror task.
In order to do so, we need to configure `CRON_EXPRESSION_FOR_OSV_MIRRORING_TASK` in `hyades > docker-compose > apiserver` to perform osv mirroring and run the api-server container.

Options of configuration for mirroring tasks need to be revisited. Same has been documented in existing issue https://github.com/DependencyTrack/hyades/issues/929

**Comment by sahibamittal** [comment]
All you need is configure below in `hyades-apiserver > application.properties`. Set it as per your need, below means 10th minute of every hour.
`task.cron.mirror.osv=10 * * * *`
No need to set `CRON_EXPRESSION_FOR_OSV_MIRRORING_TASK` explicitly in hyades.
**Closing this issue as OSV mirroring is working as expected.**
