### ISSUE TITLE
Possible incorrect value used for source.name in case of GHSA test

### ISSUE THREAD

**Issue by prabhu** [DependencyTrack/hyades#1295]
### Current Behavior

Noticed two values `GHSA` and `GITHUB` used in the unit test.

https://github.com/DependencyTrack/hyades/blob/eaee8e7db95787dce7ded7e8ea72c5c076ea5527/mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java#L72

https://github.com/DependencyTrack/hyades/blob/eaee8e7db95787dce7ded7e8ea72c5c076ea5527/mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParserTest.java#L77

These do not correspond to the official CNA short names which is either `GitHub_P` (for official GitHub projects) or `GitHub_M` (for all other projects). Here is a [script](https://github.com/AppThreat/vulnerability-db/blob/master/vdb/lib/cna.py) that can be used to collect all the CNA name and UUID values.

```
"github_m": "a0819718-46f1-4df5-94e2-005712e83aaa"
"github_p": "82327ea3-741d-41e4-88f8-2cf9e791e760"
```

The source name could be retrieved based on the UUID information if available. If not, it is safe to assume `GitHub_M` and use `GitHub_P` if the vendor is `github` (lowercased).

### Steps to Reproduce

See code

### Expected Behavior

Source name could match the official short names

### Hyades Version

latest

### Repository Type

Hyades services

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/hyades/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/hyades/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Another good spot!

At the moment, the `source` fields are populated according to Dependency-Track's [`Vulnerability.Source` enum](https://github.com/DependencyTrack/dependency-track/blob/09fdec3b39d825844d6a08f25cedb149f39385d9/src/main/java/org/dependencytrack/model/Vulnerability.java#L102-L112). That is kind of intentional, but admittedly not ideal.

The inconsistency between `GITHUB` and `GHSA` is definitely a bug.

I really like the idea of using official CNA names instead.

**Comment by nscuro** [comment]
Raised https://github.com/DependencyTrack/hyades/issues/1297 as follow-up for the CNA name suggestion.
