### ISSUE TITLE
Determine when all analyzers finished their analysis for a component

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#135]
At the moment, all analyzers do their work in parallel, and potentially at a different pace.

For CI scans however, we need a way to check when all analyzers have finished their work on a given component.

This functionality was trivial in the original API server implementation, as analyzers would run sequentially.

**Comment by japurva1502** [comment]
I can take this up

**Comment by japurva1502** [comment]
Approach : We can maintain an object which holds the analyzer completion information in the poc code against the purl and cpe in either kafka state store or in-memory data structure and each analyzer on completion updates its completion flag in the object and check if the other enabled analyzers are completed or not. If completed we send message to DT server.
Also the vulnerabilityResult will hold all the vulnerabilities found for the component in the format <source/ID> ( as mentioned by Niklas) in the interest of not exceeding the message size and along with that the Vulnerability Result also includes the information about whether the event was for purl, cpe or swidId.

DT code, since it sends the component from api server at the first hand knows whether the component contains cpe, purl or swidTagID and uses this information to wait for the response from poc for purl, cpe and swid.

So the information on analyzers completion is sent from poc code, however the completion on various event of component based on purl/cpe/swid is tracked by DT code, this way we need not to worry about the scaling up and down the application as all the analyzers for a particular event type of a component will run on same instance of kafka poc.

**Comment by japurva1502** [comment]
Approach #2: On receiving the component, the POC can send the enabled analyzers to DT and instead of maintaining completion in kafka poc in state stores/in-memory, DT can track it (everything else remains same as in above approach)

**Comment by japurva1502** [comment]
@nscuro, Currently this issue only talks about the completion for a component, should we expand it to track the completion of bom (all the components of a particular bom)?
We are currently nowhere maintaining the list of component for a bom and whether all the components are returned back to api server after analysis.

Also, as we are sending all the vulnerabilities of a component in a single message, should we skip the description for time being as limiting it to certain length is tricky as in what length to consider to have a meaningful description

**Comment by nscuro** [comment]
> Currently this issue only talks about the completion for a component, should we expand it to track the completion of bom (all the components of a particular bom)?

Yeah, the idea is once you know a given component was scanned successfully, you can determine whether this is true for the entire project ad-hoc. For example in `/api/v1/bom/token/<UUID>`, instead of [checking the `lastVulnerabilityAnalysis` timestamp for each component in the project](https://github.com/sahibamittal/dependency-track/blob/818f285fe357f4bbef00f56fa3978c9e9d77e750/src/main/java/org/dependencytrack/resources/v1/BomResource.java#L312-L319), check their analysis status.

> Also, as we are sending all the vulnerabilities of a component in a single message, should we skip the description for time being as limiting it to certain length is tricky as in what length to consider to have a meaningful description

Did you run into issues with the descriptions being included? If you did, maybe look into [compression](https://www.conduktor.io/kafka/kafka-message-compression) and see if that helps?

**Comment by nscuro** [comment]
This could be relevant here: https://github.com/mehab/DTKafkaPOC/pull/174#issuecomment-1368969002

**Comment by nscuro** [comment]
The current implementation is only reporting which analyzers are enabled, but not what of those are actually capable of analyzing the component. A component with a CPE but no PURL will not be analyzed by OSS Index or Snyk, the API would never receive results from them.

**Comment by nscuro** [comment]
The API server implementation uses an in-memory hashmap, which is a bit unfortunate. As the events in Kafka are persistent, I think the API server should be able to determine the completion even if it was restarted between receiving of events for a given component. 

It'd be great if we could solve this using Kafka Streams tools (KTable, joins, etc.). That way it would be persistent but wouldn't stress the database.

**Comment by nscuro** [comment]
Solution based on Kafka Streams implemented in #219.
