### ISSUE TITLE
Calculate portfolio metrics in Kafka Streams

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#284]
Portfolio metrics are currently calculated in the API server, using three separate tasks:

* [`ComponentMetricsUpdateTask`](https://github.com/DependencyTrack/dependency-track/blob/4.7.0/src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java): Does the heavy lifting of gathering information about a given component from the database
  * Number of `CRITICAL`, `HIGH`, `MEDIUM`, `LOW`, `UNASSIGNED` severity vulnerabilities
  * Total number of vulnerabilities
  * Total number of findings, but also:
    * Number of audited findings
    * Number of unaudited findings
    * Number of suppressed findings
  * Number of `FAIL`, `WARN`, `INFO` policy violations
  * Total, audited, unaudited numbers of policy violations per type:
    * `LICENSE`, `OPERATIONAL`, `SECURITY`
* [`ProjectMetricsUpdateTask`](https://github.com/DependencyTrack/dependency-track/blob/4.7.0/src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java): Kicks off a `ComponentMetricsUpdateTask` for each component in a given project, and aggregates the resulting metrics.
* [`PortfolioMetricsUpdateTask`](https://github.com/DependencyTrack/dependency-track/blob/4.7.0/src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java): Kicks off multiple `ProjectMetricsUpdateTask`s in parallel, one for each project in the portfolio. Aggregates resulting metrics.

Metrics calculation has historically been one of the most expensive operations in DT, especially for large portfolios.
But not only is it resource-intensive, its batch-processing nature also causes lags between the time something changes (new vulnerability discovered), to it being reflected in the metrics.

While component and project metrics may be updated frequently, changes in these metrics will not be reflected in overall portfolio metrics until `PortfolioMetricsUpdateTask` was executed.

Per default, `PortfolioMetricsUpdateTask` is [scheduled](https://github.com/DependencyTrack/dependency-track/blob/7cfc466baf7548ddb758f9e7b008b2d4aaedd148/src/main/java/org/dependencytrack/tasks/TaskScheduler.java#L98-L99) to run every hour. It can be triggered manually by users with `PORTFOLIO_MANAGEMENT` permission.

---

Both `ProjectMetricsUpdateTask` and `PortfolioMetricsUpdateTask` don't really do anything by themselves, besides aggregating. 

Ideally, anytime the metrics for a component change, the corresponding project metrics should be updated in almost real time. The same should be true for portfolio metrics whenever project metrics change.

Using Kafka Streams, it should be possible to model component metrics as a stream of events. These events could be [aggregated](https://kafka.apache.org/33/documentation/streams/developer-guide/dsl-api.html#aggregating) based on the UUID of the project the components belong to. Project metrics aggregates themselves can emit a stream of events, which, again, could be aggregated into portfolio metrics. 

Theoretically, that would leave is with 3 topics:

* `dtrack.metrics.component`
* `dtrack.metrics.project`
* `dtrack.metrics.portfolio`

Consumers of these topics could either:

* Materialize the data in their own database
* Stream them directly to users via Websockets, allowing for almost real time dashboards

Note that, in order to display these metrics as time series graph, consumers will still need to track individual data points themselves. The streams mentioned above will only ever contain the most recent data point per component or project.

---

A few complications I see here:

* Metrics numbers can go up and down. How do we handle subtractions from an aggregate?
* Components and projects may get deleted. How do we handle removals from an aggregate?

**Comment by nscuro** [comment]
Here's the diagram that we scribbled in our brainstorming session:

![Untitled-2023-02-10-1430(1)](https://user-images.githubusercontent.com/5693141/218126857-c301a132-9fdf-4383-904c-2953ff4b0043.png)

The idea is to keep track of the "last known" metrics for every component in a "Delta Processor", using a key-value state store. By comparing new incoming events with the last known value, we can calculate "Delta Events", and forward those to the aggregation instead. Component deletions can be signaled using tombstone events, which would have to be sent by the API server whenever a component is removed in its database.

Project metrics will still have to be consumed by the API server, and portfolio metrics still need to be calculated according to the access level of the user viewing them. But at least the delay of propagation between component- and project metrics is improved, and there's no need to re-calculate component metrics every time the project metrics are refreshed.

It is likely that the API server DB can be improved to handle time series data more efficiently. 

However, using a dedicated time series DB is another option we could consider.

**Comment by mehab** [comment]
Summarizing the discussion done so far with @VithikaS 

There are only two places in the existing dependency track application where the portfolio metrics update is being handled:
The taskScheduler triggers it https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/tasks/TaskScheduler.java#L96 or the metricsResource https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/resources/v1/MetricsResource.java#L162 . 

- The initial thought process is to get rid of the metrics update from the task scheduler(?) and have it everytime there is a new component for which the vulnerabilityAnalysis is mentioned as complete by the hyades server. In the later phases this completion would also include policyViolation calculations completed. But for now policyViolations is being handled by the apiserver and is not being taken into account for metrics update task. 
- When vulnerabilityAnalysis is complete for a component, both hyades and api server would be made aware of the completion. At this stage, if at the hyades end, the lastSeen ktable has an entry for that particular component, we will use the information on the analysisComplete topic to calculate the delta for the component, update the last seen ktable and then forward information to aggregator. 
- On the other hand, if the lastSeen ktable does not have information about this component, then an event would be sent to the hyades api server that would then produce component information and all required counts on a topic as an event after reading it from the db. Once this info is obtained, the lastSeenKtable would be updated by the delta processor with the latest counts, referring the vulnerabilityAnalysisComplete information from the respective topic. This would also mean that the hyades api server needs to be sent back this updated data to be stored in the db to keep the db in sync. 
- Since the lastSeenKTable is going to be large, should we use it as a persistentStorage type rather than inMemory( as done in the VulnerabilityAnalysisTopology?)
- For every end point in the resource file that is doing a getMetrics, we should use the output from above calculation and remove db interaction at this place
- Should the VulnerabilityMetricsUpdateTask be dealt with in the same approach?
