### ISSUE TITLE
Rework frontend for hyades

### ISSUE THREAD

**Issue by sahibamittal** [DependencyTrack/hyades#466]
Currently, we use dependency-track frontend which allows users to customise properties such as GitHub datasource properties.
However, when integrated with hyades-apiserver, these configurations are only set in backend.

To avoid frontend-backend mismatch:

1. Either remove such configurable options from frontend. (need Hyades-frontend)
2. OR make such properties configurable in backend from frontend.

**Comment by sahibamittal** [comment]
Thoughts on options above:

1. We don't want to have a separate frontend (too much of additional work and maintenance).
2. Not preferable to send secrets between services.

Also, the properties will be configurable by limited number of admins, it will not affect the end-user interaction. 
We can park it for now until we come up with viable solution.

**Comment by mehab** [comment]
We also need to add changes to the front end so that the project_vulnerability_analysis_complete notification is supported on the UI instead of having to use api put request manually to perform this action.
This notification is added to address the [issue](https://github.com/DependencyTrack/hyades/issues/573) and the PR that needs this UI change is [here](https://github.com/DependencyTrack/hyades/pull/593)

**Comment by sahibamittal** [comment]
This issue can be closed as separate repository [Hyades-frontend](https://github.com/DependencyTrack/hyades-frontend) has already been created to support Hyades.
