### ISSUE TITLE
Proposal: Moving Mirroring Tasks On to Quarkus Application

### ISSUE THREAD

**Issue by japurva1502** [DependencyTrack/hyades#55]
Current Implementation: 
Currently the DT performs Mirroring of GitHub, OSV, NVD and EPSS on the scheduled time and also when user updates the config on the UI to enable mirroring for particular advisory.
In Current implementation, we sequentially download, parse and add vulnerabilities from the URL
Few bottlenecks with current approach:
1. Mirroring happens in DT and take lot of CPU and can interfere with other functionality of DT
2. All the ecosystems ( in case of OSV) and api hit for each year (NVD) happens sequentially, taking lot of time

Proposed Architecture:
Move the mirroring tasks out from DT to Quarkus Application and run the ecosystems in parallel.
Few positives outcomes from this approach:
1.The DT server can be offloaded from the mirror task and this could enhance the performance of DT
2.Parallel download of ecosystems can speed up the mirroring, however since the database remains with the DT, parallel processing of mirroring tasks could cause too many update requests to Database.
3. Can achieve parallelism using kafka streams consumer, which could be dynamically scaled

A rough sketch around the proposal : https://excalidraw.com/#room=2eabf2bfa48e3cdc9dd3,jrGbPL7Vgn2RwAXTnxeceg

**Comment by nscuro** [comment]
* Parallelization of downloads in the Quarkus app are unlikely to yield a noticeable performance
    improvement, if it's still the API server that needs to take care of persisting / synchronizing the data.
* The internal analyzer needs access to vulnerability data in order to do its job.
    Accessing a Kafka stream via KTable etc. to query for vulnerabilities will most likely not be sufficient.
    If vulnerabilities are kept in the API server database, and the API server is in charge of managing them,
    then the Quarkus app would need database access to run the internal analyzer.
* Which service "owns" the vulnerability data?
    If we move ownership to the Quarkus app, then how will the API server access it?

**Comment by japurva1502** [comment]
I was thinking that the Vulnerability data ownership we can keep with DT, as we need database interaction for that and in quarkus service we do the download and parse and send final Vulnerability object back to DT

**Comment by japurva1502** [comment]
Thinking if we could keep the vulnerability data in DT itself and when we move internal analysis task on to quarkus service, we fetch the Vulnerability data from DT using REST call

**Comment by nscuro** [comment]
I was thinking about this is a little more, and I think we can still make Kafka the single source of truth for vulnerability data. But it requires consuming applications to "materialize" the data into their own database. And with database I don't mean key value stores like RocksDB built-in to Kafka Streams, but SQL (or document-based NoSQL) databases. With KV stores we can only query by key, which is insufficient for all operations we need to perform.

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/5693141/208309505-8d5a4ddf-8ce9-44d5-8a19-0d4081cac40b.png">

The internal analyzer really only needs the affected coordinates and version ranges. It could consume from the `dtrack.vulnerability` topic and "materialize" the data it needs into an H2 database (when only a single vulnerability analyzer instance is deployed), or a Postgres / MSSQL server (when multiple instances are deployed). 

In this scenario, the vulnerability analyzer would not have to connect to the API server database.

Because the `dtrack.vulnerability` topic uses [compaction](https://developer.confluent.io/learn-kafka/architecture/compaction/), only the latest value for each key is kept. Updating a vulnerability is simply a matter of re-publishing the new state to the topic. Deletions are possible via tombstones (publishing a `null` value for the key of the vulnerability to be deleted). 

An open question is how we want to handle data for the same vulnerability from different sources. By using the `<source>/<id>` format for keys, we'd get different entries for `GHSA-123` from GitHub and OSV. This allows us to track what exactly each source reported, but at some point we'll have to correlate this data. If we just use vulnerability IDs as keys, then GitHub and OSV will end up overriding each other's data all the time.
